"""empty message

Revision ID: 18af19aef726
Revises: c0e8fabea42e
Create Date: 2021-07-19 13:13:04.750158

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '18af19aef726'
down_revision = 'c0e8fabea42e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'password')
    # ### end Alembic commands ###
