"""empty message

Revision ID: c0e8fabea42e
Revises: 5fa55dae0614
Create Date: 2021-07-19 13:12:49.365744

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'c0e8fabea42e'
down_revision = '5fa55dae0614'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'password')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password', postgresql.BYTEA(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
